

export const RECEIVE_CATEGORYS = 'RECEIVE_CATEGORYS';
export const RECEIVE_BRAND = 'RECEIVE_BRAND';
export const RECEIVE_HOMEPAGE = 'RECEIVE_HOMEPAGE';
export const RECEIVE_ALLBRANDS = 'RECEIVE_ALLBRANDS';
export const RECEIVE_ACTIVITY='RECEIVE_ACTIVITY';
